spring.application.name=Spring_Security

spring.security.user.name = potter
spring.security.user.password=halfblood

spring.datasource.url=jdbc:mariadb://localhost:3306/springStarter
spring.datasource.username=springuser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect